# Generated by Django 4.1 on 2022-08-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancestudents',
            name='status',
            field=models.CharField(choices=[('at lesson', 'at lesson'), ('reasonable', 'reasonable'), ('not reasonable', 'not reasonable')], default='at lesson', max_length=30),
        ),
    ]
